### ISSUE TITLE
PushNotificationsAPI : Failed to register device: NOKResponse(error=Something went wrong, description=Device could not be created)

### ISSUE THREAD

**Issue by andrewindayang** [pusher/push-notifications-android#150]
Please fix this issue please...

for the PushNotificationsAPI giving us a pain where the error to be 
**### Failed to register device: NOKResponse(error=Something went wrong, description=Device could not be created)**

**Comment by JonathanCaspar** [comment]
This is a duplicate of https://github.com/pusher/push-notifications-android/issues/149

**Comment by IlijaAntrax** [comment]
I'm also getting this error in console, notifications do not work on Android phone, i do not get one in message receive listener.
It start happening after i update sdk to 34 and android gradle plugin. Libraries updated as well.

**Comment by IrynaDoroshenkoDev** [comment]
I also have an issue PushNotificationsAPI    com.myfamilychannel.familyapp    W  Failed to register device: NOKResponse(error=Unauthorized, description=The device token provided could not be validated against any known credentials). IOS works just fine. android 34 as well.

**Comment by johankladder** [comment]
Same here. It seems to be working in sdk < 34, but not in 34. The device is not receiving any push notifications. The thing is, this error is only visible in console, so it took a while when I found it.

Also the  `PushNotifications.setUserId` is not responding with a failure callback, nor a success - which seems to be related to the mentioned bug.

**Comment by ashusainirv** [comment]
Is there any update on this issue ?

**Comment by dhruvpvx** [comment]
@deeborania can you please release a new version from main branch 
I can see that issue is already fixed but need to release a new version

**Comment by s4m4n** [comment]
Any updates on this issue?

**Comment by dhruvpvx** [comment]
This has been an ongoing issue for almost three months, and the Pusher Beams team hasn’t released an update despite having fixed it. We’ve already migrated from Pusher Beams to WonderPush. It’s a great tool that is cheaper, offers many features, and has an almost 100% delivery rate. Their customer support is also excellent, and I highly recommend giving it a try.

**Comment by s4m4n** [comment]
There's a 1.10.0 on MVN released on Oct 2nd, but I cannot confirm the issue is fixed. Can anyone give it a try? 

https://mvnrepository.com/artifact/com.pusher/push-notifications-android

**Comment by Atraxmaster** [comment]
This released 1.10 not working

**Comment by IrynaDoroshenkoDev** [comment]
Not working for me as well

**Comment by s4m4n** [comment]
I just migrated to Firebase and set everything up within an hour. There will be no more discussions with the Pusher team, which has no responsibility. Move on!

@IrynaDoroshenkoDev
@Atraxmaster

**Comment by bennygrahn** [comment]
This still not fixed? How can a company as Pusher not fix this issue as we cant send notifications to Android users ?!

**Comment by aonemd** [comment]
Hello everyone!

Ever since [the deprecation of the Legacy FCM APIs](https://firebase.google.com/docs/cloud-messaging/migrate-v1), we have seen this issue with multiple clients. What helped us solve it was:


1. Downloading the latest google_services.json file from the android console for your app. Update this in the application directory of your android [how to](https://pusher.com/docs/beams/getting-started/android/configure-fcm/?ref=docs-index#download-the-firebase-configuration-file).

2. In the root level (project) `build.gradle` file use the following dependencies:

```
    id("com.google.gms.google-services") version "4.4.2" apply false
```

3. In the application (module) build.gradle file use the following dependencies:

```
    implementation("com.google.firebase:firebase-messaging:22.0.0")
    implementation("com.google.firebase:firebase-iid:21.1.0")
    implementation("com.pusher:push-notifications-android:1.10.0")
``` 

We have tested this with SDKs 33, 34, and 35 and for all the tests, we have successfully acquired an FCM token and received notifications.

**Comment by aonemd** [comment]
> I also have an issue **PushNotificationsAPI Failed to register device: NOKResponse(error=Unauthorized, description=The device token provided could not be validated against any known credentials)**. IOS works just fine. Android with Pusher -doesn't work
> 
> build.gradle : // React Native Pusher Notifications implementation 'com.google.firebase:firebase-core:21.1.1' implementation 'com.google.firebase:firebase-messaging:22.0.0' implementation "com.google.firebase:firebase-iid:21.1.0" implementation 'com.pusher:push-notifications-android:1.9.2' implementation project(':react-native-pusher-push-notifications') testImplementation 'junit:junit:4.12'
> 
> classpath 'com.google.gms:google-services:4.4.2'
> 
> Android SDK=34
> 
> My Results:
> 
> 1. I've registered the Pusher beam successfully with the correct key;
> 2. Registered a user successfully;
> 3. get it's ID successfully;
> 4. Subscribed on interests successfully;
> 5. I've got a token from the API for pusher - looks correct for the correct user and with exp in the 1 day (24h as in the tutorial);
>    6)FCM token works I tested it via Firebase console, and all pushes in all states work;
> 6. But I still see all the time an error: **_PushNotificationsAPI : Failed to register device: NOKResponse(error=Unauthorized, description=The device token provided could not be validated against any known credentials)_**

Hi @IrynaDoroshenkoDev, this react-native is a 3rd party implementation and is not maintained by us and as you see [here](https://github.com/b8ne/react-native-pusher-push-notifications/blob/master/android/build.gradle#L52), it's using older dependencies.

**Comment by jaime-gomez** [comment]
This is still not working, even on the latest versions. Getting this error every time and no push notifications. `Failed to register device: NOKResponse(error=Something went wrong, description=Device could not be created)`

**Comment by aonemd** [comment]
Hey @jaime-gomez We can't reproduce the issue on our setup. Can you provide an example app with the dependencies you are using that we can test?

**Comment by ashusainirv** [comment]
@aonemd Finally It worked, Thanks a lot 

> Hello everyone!
> 
> Ever since [the deprecation of the Legacy FCM APIs](https://firebase.google.com/docs/cloud-messaging/migrate-v1), we have seen this issue with multiple clients. What helped us solve it was:
> 
> 1. Downloading the latest google_services.json file from the android console for your app. Update this in the application directory of your android [how to](https://pusher.com/docs/beams/getting-started/android/configure-fcm/?ref=docs-index#download-the-firebase-configuration-file).
> 2. In the root level (project) `build.gradle` file use the following dependencies:
> 
> ```
>     id("com.google.gms.google-services") version "4.4.2" apply false
> ```
> 
> 3. In the application (module) build.gradle file use the following dependencies:
> 
> ```
>     implementation("com.google.firebase:firebase-messaging:22.0.0")
>     implementation("com.google.firebase:firebase-iid:21.1.0")
>     implementation("com.pusher:push-notifications-android:1.10.0")
> ```
> 
> We have tested this with SDKs 33, 34, and 35 and for all the tests, we have successfully acquired an FCM token and received notifications.

**Comment by jaime-gomez** [comment]
Hey @aonemd I have the same dependecies, also the the pusher java client 2.4.4 which we use to receive pusher events, that one is working fine and events are coming as espected, but when we add `PushNotifications.start` and `PushNotifications.addDeviceInterest` we keep on getting the error of `device could not be created`

**Comment by ashusainirv** [comment]
@jaime-gomez That got fixed after this step,

Downloading the latest google_services.json file from the android console for your app. Update this in the application directory of your android [how to](https://pusher.com/docs/beams/getting-started/android/configure-fcm/?ref=docs-index#download-the-firebase-configuration-file).

Note : you have to update your local file as well as on beams.

**Comment by jaime-gomez** [comment]
I've also done that, app and beams console have the latest json file, same scenario, no notifications arriving

**Comment by jaime-gomez** [comment]
Hi @aonemd I've uploaded again the `google.services.json` file again on the beams console, created a new dummy project with only this dependency and only start push notifications and still i'm getting the same error, and in the console the `waiting for device` button never ends indicating that the connection never took place. If you send me and email address I can send you the dummy project so you guys can check

**Comment by aonemd** [comment]
Hey @jaime-gomez , could you send it to us on support@pusher.com? Thanks 🙏

**Comment by Shazin12** [comment]
still getting this issue

**Comment by ilhamwd** [comment]
getting this issue after upgrading to AGP 8.7.0 (was 8.2.1 and Pusher worked)

**Comment by raghavji2050** [comment]
My issue is that I am uploading the wrong file.

There are two files:
1. Firebase Configuration File 
2. FCM service account JSON.

I am uploading the Firebase Configuration File, but need to upload FCM service account JSON.

After correcting this and uploading the proper FCM service account JSON, the issue was resolved. Looks like docs is not clear
